### ISSUE TITLE
Grid for Personal Details and Address

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/volunteer-form#1]
Hi Christina,
@cmuxlow 

I've encountered an issue with my grid for the medium and large screen sizes. For the Personal Details and Address sections, the rows are supposed to share two units on one row (i.e. Full Name and What would you like to be call? are supposed to be in the same row). So I've gone ahead and formatted the units as m-1-2 and l-1-2, however the grids are not lining up to have 2 units in one row. Any advice as to how I could make changes to correct this?

Also a quick aside, I was having trouble styling the radio and checkboxes as the borders are supposed to be a green shade. I tried a few different things and was unable to change the border colour from grey to green. Do you know how I could go about doing that?

Thanks in advance,
Rianna

**Comment by ghost** [comment]
Hey, just transferring this to my new github name @muxlowc

Will answer soon..

**Comment by muxlowc** [comment]
@riannazandbelt  so you currently have all of your items inside of one unit. 

Do this instead:

1) change this div: 
`<div class="unit xs-1 s-1 m-1 l-1 border pad-b-2 pad-t-2">`
to this:
`<fieldset class="pad-b-2 pad-t-2">`  
(remember that fieldsets are used to group relevant information, which is what you need in this case. And remember to change your closing </div to a closing </fieldset)

2) move your "grid" class down into a div thats directly after your "legend":
```
 <fieldset class="pad-t-1-2">
        <legend class="gutter-1-2 giga push">Personal details</legend>

        <div class="grid">
          <div class="unit xs-1 s-1 m-1-2 l-1-2 push gutter-1-2">
            <label for="full-name" class="push-1-8">Full name</label>
            <input id="full-name" class="push-1-8" required>
```

This is make all of your units have a direct "grid" parent.

Hope this helps!

**Comment by riannazandbelt** [comment]
@muxlowc thanks for your help, it worked!

I'm almost done the form as all my screenshots have been accepted, the last issue I'm encountering when I run it through Markbot is the following:

* Lines 210, 225, 240: There should be nothing directly inside the .grid except elements with the class .unit
* The website isn't functioning as expected: More than one label's **for** attribute points to the **id** of **name**

From looking at the code, all I can see inside the .grid tags are .unit classes with the label and input inside of those divs (is that incorrect?). And I thought the **for** and **id** tags had to be the same to link them together?

Thanks again,
Rianna

**Comment by muxlowc** [comment]
@riannazandbelt 

Ah, so it looks like you're trying to have a grid inside of a grid, but you are closing your units without putting the grids directly inside of it.

1) So what you can do is remove your "grid" class from lines 209/224/239, as well as your units from Lines 210/225/240. You're putting this in units where they are 100% at all browser sizes, so a unit isn't really even necessary there (they'll be 100% by default) - your other grids/units should be good now

2) Name's need to change depending on which question is being asked.. for example: you have the name="" set to "agree" to two of the radio button questions - so now your code doesn't see that these are two separate questions..So for the Driver licence question you could have all inputs have name="licence", and the Pick-up Truck question you could have all input answers have "name="truck" etc..

Each set of questions needs a specific "name" to differentiate between each question.
